shared Open_Order_Report = let
    Source = Csv.Document(Web.Contents("https://3492685.app.netsuite.com/core/media/media.nl?id=2600949&c=3492685&h=<REDACTED>&_xt=.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Ship Date", type date}, {"Document Number", type text}, {"Sales Rep", type text}, {"Territory", type text}, {"Company Name", type text}, {"Cust Terms", type text}, {"SO Terms", type text}, {"Status", type text}, {"Inventory Location", type text}, {"PO/Check Number", type text}, {"Item", type text}, {"Item Rate", type number}, {"Amount Discounted", type number}, {"Qty Committed", Int64.Type}, {"Amount Ready To Ship", type number}, {"Back Order Qty", Int64.Type}, {"Back Order Amount", type number}, {"Commit", type text}, {"Amount Unbilled", type number}, {"Balance", type number}, {"Credit Limit", Int64.Type}, {"Credit Limit Notes", type text}, {"Credit Hold", type text}, {"Product Category", type text}}),
    #"Grouped Rows" = Table.Group(#"Changed Type", {"Ship Date", "Territory", "Item"}, {{"BO", each List.Sum([Back Order Qty]), type nullable number}}),
    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Days From Today", each Duration.Days([Ship Date]-Date.From(DateTime.LocalNow()))),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Days From Today", Int64.Type}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type2", "dFulfillment Location", each if [Territory] = "B2B China" then "Direct" else if [Territory] = "B2B United States" then "JAX" else if [Territory] = "B2B Asia Pacific" then "Direct" else if [Territory] = "B2B Europe" then "Direct" else if [Territory] = "B2B Canada" then "JAX" else if [Territory] = "B2C United States" then "JAX" else if [Territory] = "B2B Middle East & Africa" then "JAX" else if [Territory] = "B2B Japan" then "Direct" else if [Territory] = "B2B China/Supplier" then "JAX" else if [Territory] = "B2B Latin America" then "JAX" else null),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Tradeline", each if [Territory] = "B2B China" then "AP" else if [Territory] = "B2B United States" then "Americas" else if [Territory] = "B2B Asia Pacific" then "AP" else if [Territory] = "B2B Europe" then "EMEA" else if [Territory] = "B2B Canada" then "Americas" else if [Territory] = "B2B Latin America" then "Americas" else if [Territory] = "B2B Middle East & Africa" then "EMEA" else if [Territory] = "B2B Japan" then "AP" else null)
in
    #"Added Conditional Column1";
